import { Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { Providers } from "@/app/Providers";
import Footer from "@/components/Footer/Footer";

const opensans = Open_Sans({
  variable: "--font-open-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      data-theme="light"
      className={` ${opensans.className} } h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <main>
          <Providers>
            <Navbar />
            {children}
            <Footer />
          </Providers>
        </main>
      </body>
    </html>
  );
}
